apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  ports:
    -  name: ftps
       port: 21
       targetPort: 21
    -  name: ftps-port0
       port: 2100
       targetPort: 2100
    -  name: ftps-port1
       port: 2101
       targetPort: 2101
    -  name: ftps-port2
       port: 2102
       targetPort: 2102
    -  name: ftps-port3
       port: 2103
       targetPort: 2103
    -  name: ftps-port4
       port: 2104
       targetPort: 2104
    -  name: ftps-port5
       port: 2105
       targetPort: 2105
    -  name: ftps-port6
       port: 2106
       targetPort: 2106
    -  name: ftps-port7
       port: 2107
       targetPort: 2107
    -  name: ftps-port8
       port: 2108
       targetPort: 2108
    -  name: ftps-port9
       port: 2109
       targetPort: 2109
    -  name: ftps-port10
       port: 2110
       targetPort: 2110
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - imagePullPolicy: Never
        image: ftps_service
        name: ftps
        livenessProbe:
          exec:
            command:
            - sh
            - health.sh
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 2100
          name: ftps-port0
        - containerPort: 2101
          name: ftps-port1
        - containerPort: 2102
          name: ftps-port2
        - containerPort: 2103
          name: ftps-port3
        - containerPort: 2104
          name: ftps-port4
        - containerPort: 2105
          name: ftps-port5
        - containerPort: 2106
          name: ftps-port6
        - containerPort: 2107
          name: ftps-port7
        - containerPort: 2108
          name: ftps-port8
        - containerPort: 2109
          name: ftps-port9
        - containerPort: 2110
          name: ftps-port10