apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  ports:
    -  name: phpmyadmin
       port: 5000
       targetPort: 5000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - imagePullPolicy: Never
        image: phpmyadmin_service
        name: phpmyadmin
        livenessProbe:
          exec:
            command:
            - sh
            - health.sh
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 5000
          name: phpmyadmin
