apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: wordpress
  ports:
    -  name: wordpress
       port: 5050
       targetPort: 5050
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - imagePullPolicy: Never
        image: wordpress_service
        name: wordpress
        livenessProbe:
          exec:
            command:
            - sh
            - health.sh
          initialDelaySeconds: 30
          periodSeconds: 10
        ports:
        - containerPort: 5050
          name: wordpress